language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r dev-requirements.txt

script:
    - py.test

deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: shir0kamii
    password:
        secure: hoDkOg5/YPuLylLs9NyrVhJ3FzkviYDDZmf7cGpPOXXiecQAV/V5p6AvmxwtAFQFHrSQSKUIu/px6t4SmPwP+DKGGzLMeCsTEJiRvqBVhqyHpfRf/bkAyi6VMtw5w1VvGGF352qHXWbDuGSwxTM6HUX5767hTYShXSEmY15CS05b7I77HC2YZvi8V+SjXtv8xdziwQEGwUtWxrlcxNO2TQwQPwVdnIXMUmaKFk9Fk7JBgjR4apzlTko/lgZjtpBPOjh6Z4UuGRK4t7Su3BRFmsNpWXgZ/Xydk4oIXl3P2z5DSj3zzcKb8qZHNiwKo9ZGzin1csRJCHLSQHpCXWqH9CqyufT+G+DotDAy3AwDMhdhoIt491oQn4zsU3O36XuIHY/dks0HHSa/OiRlxrA5rVJhldlgT3pnYj2yNsJzQNxwkb6dhwYT2F4vjRz9v2cp6YLqgmf3PTaWzmqIlPruZqBJAUe+6XjAF0jOPVfu93wCFtneB9jJafvM8Q0aEQ4xjyBE5m86l2Mz/pN7mlAgVmIZVB2+2VaWr8c1iwJ7mGMJujHxk+8x9jowkNiWlBJ+kb0LVKdC+Jvx4GlvH/GLt6VtpW9R77pnsGXv9Q9nT/JFa+8DbsLR/npBKTjZYwXSJUoXN2mpRiA8EAwYSeQehTpphJt7jxcabD6wgMRp+EQ=
    on:
        tags: true
        python: 3.6
